apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hbh5274@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluser-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx