version: '3'
services:
  postgres:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bhhan
      - POSTGRES_DB=bhhan
      - POSTGRES_PASSWORD=bhhan
    restart: always

  oauth2:
    build:
      context: ./oauth2-service/
    image: hoya0220/oauth2-service
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/bhhan
      SPRING_DATASOURCE_USERNAME: bhhan
      SPRING_DATASOURCE_PASSWORD: bhhan
      OAUTH2_JWTSIGNINGKEY: HelloWorld
      USER_USERNAME: admin
      USER_EMAIL: admin@email.com
      USER_PASSWORD: admin_password
      USER_CLIENT_ID: client@email.com
      CLIENT_SECRET: client_password
      GRANT_TYPES: password
      SCOPES: read, write
    restart: always

  dashboard:
    build:
      context: ./dashboard-service/
    image: hoya0220/dashboard-service
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/bhhan
      SPRING_DATASOURCE_USERNAME: bhhan
      SPRING_DATASOURCE_PASSWORD: bhhan
      BHHAN_USERNAME: bhhan@email.com
      BHHAN_PASSWORD: bhhanpassword
      DASHBOARD_REDIRECTURL: http://localhost:8085
      GATEWAY_URL: http://gateway:8085
      OAUTH2_USERNAME: admin@email.com
      OAUTH2_PASSWORD: admin_password
    restart: always

  career:
    build:
      context: ./career-service/
    image: hoya0220/career-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/bhhan
      SPRING_DATASOURCE_USERNAME: bhhan
      SPRING_DATASOURCE_PASSWORD: bhhan
      SPRING_PROFILES_ACTIVE: dev
      GATEWAY_URL: http://localhost:8085
    restart: always

  gateway:
    build:
      context: ./api-gateway
    image: hoya0220/api-gateway
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      CAREER_URL: http://career:8080
      OAUTH2_URL: http://oauth2:9090
      DASHBOARD_URL: http://dashboard:9000
      OAUTH2_JWTSIGNINGKEY: HelloWorld
      OAUTH2_USERNAME: client@email.com
      OAUTH2_PASSWORD: client_password
      OAUTH2_GRANTTYPE: password
    restart: always