server:
  port: ${PORT:8085}

proxy:
  timeoutMillis: 8000

resilience4j:
  bulkhead:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 10000
        failureRateThreshold: 60

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: career-service
          uri: ${CAREER_URL:http://localhost:8080}
          predicates:
            - Path=/career/**
          filters:
            - RewritePath=/career/(?<path>.*), /$\{path}
            - CircuitBreaker=myCircuitBreaker
        - id: oauth2-service
          uri: ${OAUTH2_URL:http://localhost:9090}
          predicates:
            - Path=/oauth2/**
          filters:
            - RewritePath=/oauth2/(?<path>.*), /$\{path}
            - CircuitBreaker=myCircuitBreaker
        - id: dashboard-service
          uri: ${DASHBOARD_URL:http://localhost:9000}
          predicates:
            - Path=/**
          filters:
            - CircuitBreaker=myCircuitBreaker
oauth2:
  jwtSigningKey: HelloWorld
  url: ${OAUTH2_URL:http://localhost:9090}
  username: client@email.com
  password: client_password
  grantType: password
