apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
        - name: oauth2
          image: hoya0220/oauth2-service
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: bhhan-secret
                  key: databaseUrl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bhhan-secret
                  key: databaseUserName
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bhhan-secret
                  key: databasePassword
            - name: OAUTH2_JWTSIGNINGKEY
              valueFrom:
                secretKeyRef:
                  name: bhhan-secret
                  key: oauth2JwtSigningKey
            - name: USER_USERNAME
              value: admin
            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: bhhan-secret
                  key: oauth2UserName
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bhhan-secret
                  key: oauth2UserPassword
            - name: USER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: bhhan-secret
                  key: oauth2ClientName
            - name: USER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bhhan-secret
                  key: oauth2ClientPassword
            - name: GRANT_TYPES
              value: password
            - name: SCOPES
              value: read, write
            - name: SPRING_PROFILES_ACTIVE
              value: prod
  selector:
    matchLabels:
      app: oauth2
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-service
spec:
  selector:
    app: oauth2
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
